AWSTemplateFormatVersion: '2010-09-09'
Description: >

Parameters:
  Stage:
    Type: String
    Default: cloud
    AllowedValues:
      - cloud
      # - dev
      # - stg
      # - prod

Conditions:
  IsCloud: !Equals [!Ref Stage, "cloud"]

Mappings:
  DynamoDB:
    BmonsterScheduleTable:
      cloud: bmonster-schedule-table-cloud
    BmonsterSchedulePerformerGSI:
      cloud: bmonster-schedule-performer-gsi-cloud
    BmonsterProgramTable:
      cloud: bmonster-program-table-cloud
    BmonsterReviewTable:
      cloud: bmonster-review-table-cloud

Resources:
  BmonsterEcrRepository:
    Type: AWS::ECR::Repository
    Condition: IsCloud
    Properties:
      RepositoryName: python-sam-app-bmonster

  BmonsterScheduleDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "studio"
          AttributeType: "S"
        - AttributeName: "start_at"
          AttributeType: "S"
        - AttributeName: "performer"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "studio"
          KeyType: "HASH"
        - AttributeName: "start_at"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: !FindInMap [DynamoDB, BmonsterScheduleTable, !Ref Stage]
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      GlobalSecondaryIndexes:
        - IndexName: !FindInMap [DynamoDB, "BmonsterSchedulePerformerGSI", !Ref Stage]
          KeySchema:
            - AttributeName: "performer"
              KeyType: "HASH"
            - AttributeName: "start_at"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "ttl"
            ProjectionType: "INCLUDE"

  BmonsterProgramDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "performer"
          AttributeType: "S"
        - AttributeName: "program"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "performer"
          KeyType: "HASH"
        - AttributeName: "program"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: !FindInMap [DynamoDB, BmonsterProgramTable, !Ref Stage]

  BmonsterReviewDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"
        - AttributeName: "performer_program"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "username"
          KeyType: "HASH"
        - AttributeName: "performer_program"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: !FindInMap [DynamoDB, BmonsterReviewTable, !Ref Stage]
